### ISSUE TITLE
hotel_search using json instead of simplejson

### ISSUE THREAD

**Issue by djfletcher** [Hipmunk/hipproblems#18]
Just wanted to make you all aware that on my machine [the import of simplejson](https://github.com/Hipmunk/hipproblems/blob/master/hotel_search/scrapers/common.py#L2) instead of json breaks the HTTP server, as the simplejson module can't be found.

Changing that line to `import json` fixes the issue. Swapping it with the below works too:

```python
try: import simplejson as json
except ImportError: import json
```

**Comment by bryankaplan** [comment]
Fixed by #28.
